# Generated by Django 4.1.7 on 2026-03-02 11:11

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('octofit_tracker', '0003_alter_activity_id_alter_leaderboard_id_alter_team_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='id',
            field=djongo.models.fields.ObjectIdField(auto_created=True, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='id',
            field=djongo.models.fields.ObjectIdField(auto_created=True, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='team',
            name='id',
            field=djongo.models.fields.ObjectIdField(auto_created=True, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=djongo.models.fields.ObjectIdField(auto_created=True, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='workout',
            name='id',
            field=djongo.models.fields.ObjectIdField(auto_created=True, editable=False, primary_key=True, serialize=False),
        ),
    ]
